import { useState } from "react";
import { ArrowUpRight, BookOpen, Clock3, Headphones, Mic2, Play, Radio, Sparkles, Video, type LucideIcon } from "lucide-react";

type ContentKind = "Live sessions" | "Specials" | "Behind the scenes" | "Podcast" | "Stories" | "Interviews";
type Show = { id: string; title: string; kind: ContentKind; label: string; guest?: string; date: string; duration?: string; excerpt: string; image: string; href: string; featured?: boolean; new?: boolean };

const SHOWS: Show[] = [
  { id: "live-leostaytrill", title: "LEOSTAYTRILL ft. Shoday", kind: "Live sessions", label: "Live session 01", date: "Jun 08, 2026", duration: "04:12", excerpt: "A live performance shaped by shadow, rhythm, and intimate cinematic atmosphere.", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&h=760&fit=crop&auto=format", href: "https://www.youtube.com/watch?v=lxo0l5Mow_4&list=RDlxo0l5Mow_4&start_radio=1", featured: true, new: true },
  { id: "special-ycee", title: "YCEE — Lemonade", kind: "Specials", label: "Studio special", date: "May 24, 2026", duration: "03:48", excerpt: "A bold, stripped-back performance captured in the EchooRoom light.", image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=900&h=600&fit=crop&auto=format", href: "https://www.youtube.com/watch?v=JpJSbZEpWew", new: true },
  { id: "bts-cut-room", title: "The Cut Room Diaries", kind: "Behind the scenes", label: "Field notes 04", date: "May 12, 2026", excerpt: "A look inside the room where every frame is tuned for sound and shadow.", image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=900&h=600&fit=crop&auto=format", href: "https://www.youtube.com/watch?v=VYOjWnS4cMY" },
  { id: "podcast-synths", title: "Synths & Sovereignty", kind: "Podcast", label: "EchoFreq · Ep. 89", guest: "with Odunsi The Engine", date: "May 02, 2026", duration: "58:12", excerpt: "On influence, ritual, creative blocks, and the pressure of staying iconic.", image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=900&h=600&fit=crop&auto=format", href: "https://www.youtube.com/watch?v=F7rHps6VWIU", new: true },
  { id: "story-attention", title: "Attention is the new currency", kind: "Stories", label: "The EchooRoom journal", date: "Apr 18, 2026", excerpt: "Why the most valuable media brands are building trust before they build reach.", image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&h=600&fit=crop&auto=format", href: "/stories/attention-is-the-new-currency" },
  { id: "interview-roundtable", title: "The Creative Roundtable", kind: "Interviews", label: "Conversation 24", guest: "with Falz & Simi", date: "Apr 06, 2026", duration: "1:02:44", excerpt: "A conversation on creative independence, the business of music, and owning your masters.", image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=900&h=600&fit=crop&auto=format", href: "https://www.youtube.com/watch?v=7QU9mvNHnKg" },
];

const CATEGORIES: { label: ContentKind; icon: LucideIcon; color: string }[] = [
  { label: "Live sessions", icon: Radio, color: "text-rose-400" }, { label: "Specials", icon: Sparkles, color: "text-amber-400" },
  { label: "Behind the scenes", icon: Video, color: "text-sky-400" }, { label: "Podcast", icon: Headphones, color: "text-emerald-400" },
  { label: "Stories", icon: BookOpen, color: "text-violet-400" }, { label: "Interviews", icon: Mic2, color: "text-orange-400" },
];

function CategoryIcon({ kind, className = "" }: { kind: ContentKind; className?: string }) {
  const category = CATEGORIES.find(({ label }) => label === kind);
  const Icon = category?.icon ?? Video;
  return <Icon className={`${category?.color ?? "text-primary"} ${className}`} />;
}

function ShowCard({ show }: { show: Show }) {
  const external = show.href.startsWith("http");
  return (
    <a href={show.href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined} className="group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">
      <div className="relative aspect-[4/3] overflow-hidden rounded-sm bg-muted">
        <img src={show.image} alt={`${show.title} — ${show.kind}`} className="h-full w-full object-cover grayscale-[35%] transition duration-700 group-hover:scale-105 group-hover:grayscale-0" loading="lazy" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" />
        <div className="absolute left-4 top-4 flex items-center gap-2">{show.new && <span className="bg-primary px-2 py-1 font-mono text-[9px] uppercase tracking-widest text-primary-foreground">New</span>}<span className="flex items-center gap-1.5 bg-black/55 px-2 py-1 font-mono text-[9px] uppercase tracking-widest text-white/80 backdrop-blur-sm"><CategoryIcon kind={show.kind} className="size-3" />{show.kind}</span></div>
        <div className="absolute bottom-4 left-4 right-4 flex items-end justify-between"><span className="font-mono text-[10px] uppercase tracking-widest text-white/60">{show.label}</span>{show.duration && <span className="flex items-center gap-1 bg-black/55 px-2 py-1 font-mono text-[10px] text-white/75"><Clock3 size={11} />{show.duration}</span>}</div>
        <span className="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 transition duration-300 group-hover:opacity-100"><span className="flex size-12 scale-75 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-xl transition duration-300 group-hover:scale-100"><Play size={16} fill="currentColor" /></span></span>
      </div>
      <div className="pt-4"><div className="mb-2 flex items-center justify-between font-mono text-[10px] uppercase tracking-widest text-muted-foreground"><span>{show.date}</span><ArrowUpRight size={14} className="opacity-0 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:opacity-100" /></div><h3 className="font-display text-xl font-black leading-tight transition-colors group-hover:text-primary">{show.title}</h3>{show.guest && <p className="mt-1 text-sm text-muted-foreground">{show.guest}</p>}<p className="mt-3 line-clamp-2 text-sm leading-relaxed text-muted-foreground">{show.excerpt}</p></div>
    </a>
  );
}

export default function Shows() {
  const [activeCategory, setActiveCategory] = useState<ContentKind | "All">("All");
  const featured = SHOWS.find((show) => show.featured) ?? SHOWS[0];
  const episodes = SHOWS.filter((show) => !show.featured && (activeCategory === "All" || show.kind === activeCategory));
  const featuredExternal = featured.href.startsWith("http");

  return (
    <main className="min-h-screen bg-background">
      <header className="mx-auto max-w-[1400px] px-6 pb-12 pt-28 md:px-12 md:pt-36"><div className="max-w-3xl"><p className="mb-4 font-mono text-[10px] uppercase tracking-[0.3em] text-primary">EchooRoom / Media library</p><h1 className="font-display text-5xl font-black leading-[0.95] tracking-tight md:text-8xl">Experience worth<br /><span className="text-muted-foreground/45">staying for.</span></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-muted-foreground md:text-lg">Live sessions, honest conversations, and the stories behind the work. Explore everything we make, all in one room.</p></div><div className="mt-14 grid grid-cols-2 gap-px overflow-hidden border border-border bg-border sm:grid-cols-3 lg:grid-cols-6">{CATEGORIES.map(({ label, icon: Icon, color }) => <button key={label} onClick={() => setActiveCategory(label)} className={`flex items-center gap-3 bg-background px-4 py-4 text-left transition hover:bg-card ${activeCategory === label ? "ring-1 ring-inset ring-primary" : ""}`}><Icon size={16} className={color} /><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</span></button>)}</div></header>
      <section className="border-y border-border bg-card/40"><div className="mx-auto max-w-[1400px] px-6 py-10 md:px-12 md:py-14"><div className="mb-6 flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Now playing- This Week</p><span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Featured</span></div><a href={featured.href} target={featuredExternal ? "_blank" : undefined} rel={featuredExternal ? "noreferrer" : undefined} className="group grid overflow-hidden bg-[#0d1117] text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><div className="relative min-h-[300px] overflow-hidden"><img src={featured.image} alt={featured.title} className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-100" /><div className="absolute inset-0 bg-gradient-to-r from-black/60 to-transparent" /><div className="absolute bottom-6 left-6 md:bottom-10 md:left-10"><span className="font-mono text-[10px] uppercase tracking-widest text-primary">{featured.label}</span><h2 className="mt-3 max-w-lg font-display text-3xl font-black md:text-5xl">{featured.title}</h2></div><span className="absolute right-6 top-6 flex size-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition group-hover:scale-110"><Play size={16} fill="currentColor" /></span></div><div className="flex flex-col justify-between p-6 md:p-10"><div><p className="text-sm leading-relaxed text-white/60 md:text-base">{featured.excerpt}</p><p className="mt-6 font-mono text-[10px] uppercase tracking-widest text-white/40">{featured.date} · {featured.duration}</p></div><span className="mt-10 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-primary">Watch full session <ArrowUpRight size={14} /></span></div></a></div></section>
      <section className="mx-auto max-w-[1400px] px-6 py-16 md:px-12 md:py-24"><div className="mb-10 flex flex-col justify-between gap-5 border-b border-border pb-6 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">The archive</p><h2 className="mt-2 font-display text-3xl font-black md:text-4xl">Browse the room</h2></div><div className="flex flex-wrap gap-2"><button onClick={() => setActiveCategory("All")} className={`px-3 py-2 font-mono text-[10px] uppercase tracking-widest transition ${activeCategory === "All" ? "bg-primary text-primary-foreground" : "border border-border text-muted-foreground hover:text-foreground"}`}>All</button>{CATEGORIES.map(({ label }) => <button key={label} onClick={() => setActiveCategory(label)} className={`hidden px-3 py-2 font-mono text-[10px] uppercase tracking-widest transition sm:block ${activeCategory === label ? "bg-primary text-primary-foreground" : "border border-border text-muted-foreground hover:text-foreground"}`}>{label}</button>)}</div></div><p className="mb-8 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{episodes.length} {episodes.length === 1 ? "story" : "stories"} in {activeCategory === "All" ? "the archive" : activeCategory}</p>{episodes.length ? <div className="grid grid-cols-1 gap-x-6 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{episodes.map((show) => <ShowCard key={show.id} show={show} />)}</div> : <div className="border border-dashed border-border py-24 text-center"><p className="font-display text-2xl font-black">Nothing here yet.</p><p className="mt-2 text-sm text-muted-foreground">Check back soon for new {activeCategory.toLowerCase()}.</p></div>}</section>
    </main>
  );
}
